[tool.poetry]
name = "enviro-client"
version = "0.0.1"
description = "Enviro monitoring add-on for Raspberry Pi"
authors = ["Jordan Cook"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
enviroplus = ">=0.0.5"
font-roboto = "*"
fonts = "*"
ltr559 = ">=0.1.1"
numpy = {version = "^1.21.4", python = "<3.11"}
pillow = "^8.0"
pimoroni-bme280 = ">=0.1.1"
sounddevice = "^0.4.3"
st7735 = ">=0.0.4"
# astral
# pytz
# paho-mqtt

[tool.poetry.dev-dependencies]
black = "^21.10b0"
flake8 = "^4.0"
isort = "^5.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
line-length = 100

[tool.isort]
profile = 'black'
line_length = 100
skip_gitignore = true
