[tool.poetry]
name = "enviroplus"
version = "0.0.1"
description = "Enviro monitoring add-on for Raspberry Pi"
authors = []

[tool.poetry.dependencies]
python = "^3.7"
ads1015 = ">=0.0.7" # Sound
ltr559 = ">=0.1.1" # Light/proximity
pimoroni-bme280 = ">=0.1.1" # Humidity
st7735 = "*" # LCD
# enviroplus = ">=0.0.5"
pillow = "^8.0"
fonts = "*"
font-roboto = "*"
# astral
# pytz
sounddevice = "^0.4.3"
# paho-mqtt

[tool.poetry.dev-dependencies]

[tool.poetry.extras]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
skip-string-normalization = true
line-length = 100

[tool.isort]
profile = 'black'
line_length = 100
skip_gitignore = true
